version: '3.1'

services:
  wordpress:
    image: 'bitnami/wordpress:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/data:/bitnami'
    environment:
      - MARIADB_HOST=databasewordpress.mysql.database.azure.com
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=SQLUser@databasewordpress
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_PASSWORD=Password.1234!